{
 "title": "Stocks_decoded_app",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "API Call counter",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "api_call_counter_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API usage rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 0 },
   "targets": [
    { "expr": "rate(api_runtime_sum[1m])", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum by(cpu) (rate(node_cpu_seconds_total{mode=~\"system|user\"}[1m]))",
     "legendFormat": "{{cpu}}"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=~\"system|user\"}[1m]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_receive_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Read Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Write Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}